# lightning.pytorch==2.1.2
seed_everything: 42
data:
  train_chip_dir: ../dataset/ready/train/chips/
  train_label_dir: ../dataset/ready/train/labels/
  val_chip_dir: ../dataset/ready/val/chips/
  val_label_dir: ../dataset/ready/val/labels/
  metadata_path: configs/metadata.yaml
  batch_size: 16
  num_workers: 8
  platform: sentinel-2-l2a-4band
  num_classes: 2
model:
  num_classes: 2
  ckpt_path: checkpoints/clay-v1.5.ckpt
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
  metadata_path: configs/metadata.yaml
  platform: sentinel-2-l2a-4band
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 100
  accumulate_grad_batches: 1
  default_root_dir: checkpoints/segment
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: obertvalid-val-id
        project: finetune-segment-clay
        group: fixed-platform
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/segment
        auto_insert_metric_name: False
        filename: chesapeake-7class-segment_epoch-{epoch:02d}_val-iou-{val/iou:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
